config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root to: 'home#top'
  
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 140 }
  
  belongs_to :user  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  
  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
  def login_required
    redirect_to root_url unless current_user
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :login_required
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.new(post_params)
    
    if @post.save
      redirect_to posts_url, notice: '勉強内容を投稿しました'
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    ensure_correct_post
  end
  
  def update
    ensure_correct_post
    if @post.update(post_params)
      redirect_to posts_url, notice: "勉強内容を編集しました"
    else
      render :edit
    end
  end
  
  def destroy
    ensure_correct_post
    @post.destroy
    redirect_to user_url(@post.user_id), notice: '投稿を削除しました。'
  end
  
  private
  def post_params
    params.require(:post).permit(:content, :html, :css, :javascript, :jquery, :ruby, :rails, :php, :java, :go, :python, :swift)
  end
  
  def ensure_correct_post
    @post = Post.find(params[:id])
    
    if @post.user_id != current_user.id
      redirect_to user_url, notice: '権限がありません'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
    @user = User.new
  end
  
  def create
    user = User.find_by(email: session_params[:email])
    
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: 'ログインしました'
    else
      flash[:notice] = 'メールアドレスまたはパスワードが違います'
      render :new
    end
  end
  
  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end
  
  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_url, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    ensure_correct_user
  end
  
  def update
    ensure_correct_user
    
    if @user.update(user_params)
      redirect_to user_url(@user), notice: 'プロフィールを編集しました。'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
    gon.data = []
    html = 0
    css = 0
    javascript = 0
    jquery = 0
    ruby = 0
    rails = 0
    php = 0
    java = 0
    go = 0
    python = 0
    swift = 0
    
    @posts.each do | post |
      html += post.html
      css += post.css
      javascript += post.javascript
      jquery += post.jquery
      ruby += post.ruby
      rails += post.rails
      php += post.php
      java += post.java
      go += post.go
      python += post.python
      swift += post.swift
    end
    gon.data.push(html, css, javascript, jquery, ruby, rails, php, java, go, python, swift)
  end

  def index
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    
    if @user.id != current_user.id
      redirect_to user_url(@user), notice: '権限がありません'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_footer.html.erb
<footer class="footer bg-dark">
    <p class="text-muted text-center">&copy;&nbsp;tacty</p>
</footer>

app/views/home/top.html.erb
<div class="wrapper">
  <div class="image">
    <%= image_tag 'backimage.png'%>
    <div class="image-text text-center">
      <h1 class="mb-3 text-light">#100DaysOfCode</h1>
      <%= link_to 'ログイン', login_path, class: 'btn btn-secondary mr-2' %>
      <%= link_to '新規登録', new_user_path, class: 'btn btn-secondary ml-2' %>
    </div>
  </div>
  <div class="container">
    <div class="d-flex">
      <div class="w-50 my-5 text-center">
        <%= image_tag 'top.png', size: '300x300' %>
      </div>
      <div class="w-50 mx-auto my-5">
        <h2 class="my-5">#100DaysOfCodeとは</h2>
        <p class="text">Twitterでよく見かけるタグ<br>ですがツイートしただけで内容を忘れてませんか？<br>このアプリは内容と勉強時間を保持して復習することができます。<br>あなたの#100DaysOfCodeを記録してみましょう！！</p>
        <p class="text-center mt-2">
          <%= link_to 'はじめる', new_user_path, class: 'btn btn-primary ml-2' %>
        </p>
      </div>
    </div>
  </div>
  <%= render partial: 'home/footer' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daysofcode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "home", :media => "all" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js' %>
  </head>
  <body>
    <nav class="navbar navbar-default bg-dark sticky-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <% if @current_user %>
            <%= link_to '#100DaysOfCode', posts_path, class: 'navbar-brand text-white'%>
          <% else %> 
            <%= link_to '#100DaysOfCode', root_path, class: 'navbar-brand text-white'%>
          <% end %>
        </div>
        <ul class="nav ml-auto">
          <% if @current_user %>
          <li class="nav-item">
            <%= link_to posts_path, method: :get do %>
              <i class="fas fa-list text-white p-2 mt-1">&nbsp;投稿一覧</i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, method: :get do %>
              <i class="fas fa-edit text-white p-2 mt-1">&nbsp;投稿する</i>
            <% end %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to user_path(@current_user), method: :get do %>
              <i class="fas fa-user-alt text-white p-2 mt-1">&nbsp;マイページ</i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link text-white' %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to '新規登録', new_user_path, class: 'nav-link text-white' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: 'nav-link text-white' %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_form.html.erb
<%= form_with model: @post, local: true do | f | %>
<p class="mb-4 w-50 mx-auto text-muted">学習した言語の時間を入力してください</p>
<div class="d-flex flex-wrap w-50 mx-auto justify-content-between">
  <div class="form-group">
    <%= f.label :html, 'HTML'%>
    <%= f.select :html, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :css, 'CSS'%>
    <%= f.select :css, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :javascript, 'JavaScript'%>
    <%= f.select :javascript, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :jquery, 'jQuery'%>
    <%= f.select :jquery, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :ruby, 'Ruby'%>
    <%= f.select :ruby, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :rails, 'Rails'%>
    <%= f.select :rails, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :php, 'PHP'%>
    <%= f.select :php, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :java, 'Java'%>
    <%= f.select :java, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :go, 'Go'%>
    <%= f.select :go, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :python, 'Python'%>
    <%= f.select :python, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
  <div class="form-group">
    <%= f.label :swift, 'Swift'%>
    <%= f.select :swift, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15],[16,16],[17,17],[18,18],[19,19],[20,20],[21,21],[22,22],[23,23],[24,24]] %>
  </div>
</div>
<div class="form-group w-50 mx-auto">
  <%= f.label :content, '内容（140字以内で入力してください）', class: 'p-1 text-muted'%>
  <%= f.text_area :content, rows: 7, class: 'form-control' %>
</div>
<div class="d-flex w-50 mx-auto">
  <div class="w-50">
    <%= link_to '戻る', :back, class: 'text-dark p-1'%>
  </div>
  <div class="w-50 mx-auto text-right">
    <%= f.submit '更新', class: 'btn btn-primary px-4' %>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h1 class="my-5 w-25 mx-auto text-center border-bottom">投稿編集</h1>
    <% if @post.errors.any? %>
      <div class="text-danger  w-50 mx-auto">
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= render partial: 'post_form' %>
  </div>
  <%= render partial: 'home/footer' %>
</div>

app/views/posts/index.html.erb
<div class="wrapper">
  <% if flash[:notice] %>
   <div class="alert alert-primary text-center" role="alert">
     <%= flash[:notice] %>
   </div>
   <% end %>
  <div class="container">
    <h1 class="mt-5 mb-4 w-25 mx-auto text-center border-bottom">投稿一覧</h1>
    <table class="table table-hover mt-5">
      <% @posts.each do | post | %>
      <tr>
        <td>
          <%= link_to post.user.name, user_path(post.user_id), class: 'text-dark mx-3' %>
        </td>
        <td>
          <%= link_to post.content.truncate(53), post_path(post), class: 'text-dark ml-3' %>
        </td>
        <td class="w-15 text-right">
          <%= post.created_at.strftime("%Y/%m/%d %H:%M") %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <%= render partial: 'home/footer' %>
</div>

app/views/posts/new.html.erb
<div class="wrapper">
  <div class="container">
    <h1 class="my-5 w-25 mx-auto text-center border-bottom">新規投稿</h1>
    <% if @post.errors.any? %>
      <div class="text-danger  w-50 mx-auto">
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= render partial: 'post_form' %>
  </div>
  <%= render partial: 'home/footer' %>
</div>

app/views/posts/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="mt-5 d-flex justify-content-center">
      <h2 class="p-2 font-weight-normal">
        <%= @post.user.name %>
      </h2>
      <div>
        <p class="mt-3 p-1 text-muted">
          <%= @post.created_at.strftime("%Y年%-m月%-d日")%>に投稿
        </p>
      </div>
      <% if @current_user.id == @post.user.id %>
      <%= link_to edit_post_path(@post), method: :get do %>
      <i class="fas fa-pencil-alt text-muted p-1 mt-3 ml-5"></i>
      <% end %>
      <%= link_to post_path, method: :delete, data: { confirm: "投稿を削除します。よろしいですか？"} do %>
      <i class="far fa-trash-alt text-muted p-1 mt-3 ml-2"></i>
      <% end %>
      <% end %>
    </div>
    <div class="d-flex flex-wrap w-50 mx-auto justify-content-between">
      <p class="p-1">HTML&nbsp;<%= @post.html %>時間</p>
      <p class="p-1">CSS&nbsp;<%= @post.css %>時間</p>
      <p class="p-1">JavaScript&nbsp;<%= @post.javascript %>時間</p>
      <p class="p-1">jQuery&nbsp;<%= @post.jquery %>時間</p>
      <p class="p-1">Ruby&nbsp;<%= @post.ruby %>時間</p>
      <p class="p-1">Rails&nbsp;<%= @post.rails %>時間</p>
      <p class="p-1">PHP&nbsp;<%= @post.php %>時間</p>
      <p class="p-1">Java&nbsp;<%= @post.java %>時間</p>
      <p class="p-1">Go&nbsp;<%= @post.go %>時間</p>
      <p class="p-1">Python&nbsp;<%= @post.python %>時間</p>
      <p class="p-1">Swift&nbsp;<%= @post.html %>時間</p>
    </div>
    <div class="w-50 mt-4  mx-auto border rounded" style="height: 200px;">
      <p class="p-2 font-weight-normal" style="margin-bottom: 0;">
        <%= @post.content%>
      </p>
    </div>
    <div class="mt-2 w-50 mx-auto">
      <%= link_to '戻る', posts_path, class: 'text-dark p-1'%>
    </div>
  </div>
  <%= render partial: 'home/footer' %>
</div>

app/views/users/_form.html.erb
<div class="w-50 mx-auto">
  <%= form_with model: @user, local: true do | f  |%>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="wrapper">
  <div class='container'>
    <h1 class="text-center my-4">プロフィール変更</h1>
    <%= render partial: 'form'%>
  </div>
  <%= render partial: 'home/footer' %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="wrapper">
  <div class='container'>
    <h1 class="my-5 w-25 mx-auto text-center border-bottom">新規登録</h1>
    <% if @user.errors.any? %>
      <div class="text-danger  w-50 mx-auto">
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= render partial: 'form'%>
  </div>
  <%= render partial: 'home/footer' %>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <% if flash[:notice] %>
   <div class="alert alert-danger text-center" role="alert">
     <%= flash[:notice] %>
   </div>
   <% end %>
  <div class="container mt-5">
    <div class="d-flex">
      <div class="user-name w-25">
        <h2 class="pl-2 pb-2 font-weight-normal border-bottom">
          <%= @user.name %>
        </h2>
        <% if @current_user.id == @user.id %>
          <div class="pb-2 border-bottom text-muted">
            <i class="fas fa-cog">
              <%= link_to '&nbsp;プロフィールを編集する'.html_safe, edit_user_path(@user.id), class: 'text-muted'%>
            </i>
          </div>
        <% end %>
      </div>
      <div class="post-index w-75 mt-3 ml-5">
        <canvas id="myChart" width="200" height="100"></canvas>
        <table class="table table-striped mt-5">
          <% @posts.each do | post | %>
          <tr>
            <td>
              <%= link_to post.content, post_path(post), class: 'text-dark' %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
  <%= render partial: 'home/footer' %>
</div>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["HTML", "CSS", "JavaScript", "jQuery", "Ruby", "Rails", "PHP", "Java", "Go", "Python", "Swift"],
        datasets: [{
            label: '勉強時間',
            data: gon.data,
            backgroundColor: [
                'rgba(75, 192, 110, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 0, 0, 0.2)',
                'rgba(255, 0, 102, 0.2)',
                'rgba(102, 0, 204, 0.2)',
                'rgba(102, 51, 0, 0.2)',
                'rgba(0, 250, 154, 0.2)',
                'rgba(0, 255, 255, 0.2)',
                'rgba(255, 140, 0, 0.2)'
            ],
            borderColor: [
                'rgba(75, 192, 110, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 0, 0, 1)',
                'rgba(255, 0, 102, 1)',
                'rgba(102, 0, 204, 1)',
                'rgba(102, 51, 0, 1)',
                'rgba(0, 250, 154, 1)',
                'rgba(0, 255, 255, 1)',
                'rgba(255, 140, 0, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
      responsive: true, 
        scales: {
            yAxes: [{
                ticks: {
                  min: 0,
                  max: 100,
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>